### ISSUE TITLE
We expect vpc to be named 'vpc'.

### ISSUE THREAD

**Issue by sijis** [foremast/foremast#189]
We expect/assume that the vpc named for spinnaker is 'vpc'.
https://github.com/gogoair/foremast/blob/master/src/foremast/utils/vpc.py#L51

This may or may not be correct. In either case, we should better document our expectations.

**Comment by Charleygrossman** [comment]
According to (https://www.cloudconformity.com/conformity-rules/VPC/vpc-naming-conventions.html), I think these lines of code can be added (tailor regex to specific needs);

import re
    
vpc_pattern = re.compile(r'^vpc-(ue1|uw1|uw2|ew1|ec1|an1|an2|as1|as2|se1)-(d|t|s|p)-([a-z0-9\-]+)')

if all([(vpc['name'] == 'vpc' or re.search(vpc_pattern, vpc['name']) is not None), vpc['account'] == account, vpc['region'] == region]):

**Comment by jvasallo** [comment]
Simple fix inplace for now. closing!
