### ISSUE TITLE
Enable DynamoDB Triggers to AWS Lambda Pipeline

### ISSUE THREAD

**Issue by waynetaylor** [foremast/foremast#201]
Currently Foremast Lambda Pipeline supports: api-gateway, s3, sns, cloudwatch-event, cloudwatch-log

Enable DynamoDB triggers.E.g. when a record is inserted OR updated a lambda is triggered. This is achieved manually today e.g. devops need to manually add the trigger after deploying via pipeline

**Comment by jvasallo** [comment]
Feature doesn't exist and this is not documentation only. Adding additional tags and submitting a raw PR. No commitment yet to merge in.

https://github.com/gogoair/foremast/pull/294

**Comment by jvasallo** [comment]
Solved with Merge!
