### ISSUE TITLE
Plugin System

### ISSUE THREAD

**Issue by sijis** [foremast/foremast#231]
I've been really interested in setting up a plugin system which I believe will help the project tremendously.

The experimentation has been occurring in [gogoair/foremast-plugin-experiment-1](https://github.com/gogoair/foremast-plugin-experiment-1). 

My suggestion is to reorganize the project, so its something like this:

```
└── src
    ├── foremast
    │   ├── common
    │   │   └── base.py
    │   ├── dns
    │   │   ├── aws.py
    │   │   ├── base.py
    │   │   └── gcp.py
    │   └── loadbalancer
    │       ├── aws.py
    │       ├── base.py
    │       └── gcp.py
```

The general idea is that we should be able to create resources for a specific 'provider', as such:

```
my_plugin = plugin_source.load_plugin('aws')
dns = my_plugin.Dns()
dns.create(**kwargs)
```

We'd still have to define specific plugin resource 'structure' but as a first pass, I'm suggesting:
* create()
* update()
* destroy()

How does this sound?

**Comment by ak15199** [comment]
Very nice!

Are you working on a branch for this experimentation?

I always struggle with whether to set the hierarchy up as (resource)/(domain) or (domain)/(resource). At the moment, I see you're using the former. Is this the same way around as spinnaker?

**Comment by sijis** [comment]
Experimentation is on a separate repository: [gogoair/foremast-plugin-experiment-1](https://github.com/gogoair/foremast-plugin-experiment-1).

I wanted to keep our team comfortable with how the project is organized, which is currently (resource)/(provider).

When we discuss issues its rarely related to a specific provider, its more along the lines of this 'service' is borked in 'provider', so, i think, it makes sense in this context to leave the project layout as it has been.

**Comment by jvasallo** [comment]
This is moving along with PR #322 

Thanks for your work on this.
