### ISSUE TITLE
Travis Tests Broke after Moving to Foremast Org?

### ISSUE THREAD

**Issue by jvasallo** [foremast/foremast#300]
Looks like foremast tests are no longer running after we moved the org over. We should ensure that both Travis and ReadTheDocs continue to work.

**Comment by sijis** [comment]
I think it fixed Travis.
My test PR seem to be going through the paces now
https://github.com/foremast/foremast/pull/301

**Comment by e4r7hbug** [comment]
Checking Read the Docs now.

**Comment by jvasallo** [comment]
Cool stuff. Thanks folks. Saw this last night. :)

**Comment by e4r7hbug** [comment]
There's this random Profile that's a Maintainer on Read the Docs, https://readthedocs.org/profiles/gogoair/.

**Comment by jvasallo** [comment]
@e4r7hbug I have that login, Does it make sense to transition this to a generic account we own as an org?

**Comment by e4r7hbug** [comment]
We could, but I don't think we need it right now, considering all Maintainers have admin privileges.

**Comment by e4r7hbug** [comment]
We should also disable any Jenkins Jobs and start using Travis for releasing to PyPI.

**Comment by jvasallo** [comment]
@e4r7hbug 👍 to that.

**Comment by sijis** [comment]
@e4r7hbug if you configure that, we can disable that Jenkins job here that's currently doing it.

**Comment by jvasallo** [comment]
@e4r7hbug @sijis This is resolved I believe; right?

**Comment by sijis** [comment]
Should be.

**Comment by jvasallo** [comment]
Thanks! :)
