### ISSUE TITLE
NLB Support

### ISSUE THREAD

**Issue by mrthomaskim** [foremast/foremast#304]
Ideally, I'd like to see if foremast can support NLB, Mainly to support Haproxies or possible SFTP server behind NLB

**Comment by jvasallo** [comment]
Looks like Spinnaker may have added support in 1.9.0:
https://github.com/spinnaker/deck/commit/06ba3c5ad83186fd8d72d1361580d8f68b8742f7

**Comment by jvasallo** [comment]
Closing this as its a duplicate of #279
