### ISSUE TITLE
Add EFS access

### ISSUE THREAD

**Issue by mrthomaskim** [foremast/foremast#305]
There are few cases we would like to mount efs to new/existing pipeline for data persistance. Can we introduce EFS method to the foremast?

**Comment by jvasalloupgrade** [comment]
Take a peek at:
https://github.com/foremast/foremast/blob/master/src/foremast/templates/infrastructure/iam/sdb.json.j2

Are you referring to granting IAM permissions?

**Comment by sbasgall** [comment]
Hi, the required configuration to mount an EFS volume is done on the linux system itself.

Foremast doesn't touch this config, it's all driven from linux system configuration.

Foremast touches security groups, IAM, and so on but it doesn't have a role in the actual linux system configuration.

How would you propose EFS support in foremast works from a user point of view?

**Comment by mrthomaskim** [comment]
I should have clarified, I wanted to see if there's a way to associate existing efs volume with ec2 instances using security groups. Currently someone would have to _manually_ associate existing efs volume in order to mount the efs volume from ec2 instance(s)

**Comment by sijis** [comment]
I think the owner of the efs volume should add the app's SG to it. That would give the app access to that efs endpoint.

**Comment by sijis** [comment]
It's also sounds like you want something to create efs volume and do some app <--> efs association.

**Comment by mrthomaskim** [comment]
That's correct, app and efs association :)

**Comment by ak15199** [comment]
Following up on this, I'm still not sure it's a good idea to tie bits of AWS to the deployment configuration. More generically, I'm still in favor of adding cloud formation configuration within Foremast that builds and maintains the EFS volume, rather than tying an external dependency in to Foremast... although that's harder.

**Comment by mrthomaskim** [comment]
Ok no problem. I'll go ahead and close this for now. :)
