### ISSUE TITLE
Define multiple scaling policy or options for threshold, period_minutes support for scale down policy

### ISSUE THREAD

**Issue by vickyrajsharma** [foremast/foremast#338]
Need support for multiple scaling policy as spinnaker allows you to define multiple scaling policy, with the type of scaling, which will give much flexibility for defining config.

![image](https://user-images.githubusercontent.com/1567117/59850550-216cc300-9330-11e9-8fee-bca78c54c845.png)

If that will break the existing functionality or backward compatibility then we need support for defining more options for scale down policy like "threshold", "period_minutes". Right now options are very limited for scale_down and it takes defaults from scale up.

![image](https://user-images.githubusercontent.com/1567117/59850441-dbaffa80-932f-11e9-91df-32254ab45a24.png)

**Comment by jvasallo** [comment]
@vickyrajsharma Thanks for the report, the feature should be merged in! PyPI is getting updated as we speak, should hopefully be available in a few hours!

Docs updated here:
https://foremast.readthedocs.io/en/latest/configuration_files/advanced_usages/custom_scaling_policies.html
