### ISSUE TITLE
create-scaling-policy should use module entry point

### ISSUE THREAD

**Issue by sijis** [foremast/foremast#38]
create-scaling-policy currently uses the runner endpoint to get executed. I think it should probably use the module (`__main__.py`) entry point instead of the runner.

This aligns that entry point like other `create-*` ones.

**Comment by sbasgall** [comment]
At the same time it would be good to abstract create-scaling-policy to support multiple types of scaling policies. Currently it uses only an EC2 CPU based scaling policy. Supporting scaling policy types that can chosen from an application-master json file would be a great enhancement.

**Comment by ndcampbell** [comment]
@sbasgall It supports more than just CPU right now. It does Network In/Out and DiskReadBytes: http://foremast.readthedocs.io/en/latest/configuration_files/application_json.html#scaling-policy

If there is more you think would be useful, I'd totally be on board.
