### ISSUE TITLE
Add support for github gate authentication

### ISSUE THREAD

**Issue by tutte** [foremast/foremast#385]
# Request
Add support for github to authenticate to gate.

## Description
Currently there is only support for `google_iap`, but in our setup we are using github.
A working `gate_authentication` configuration could be something like this:
```
'credentials': {
  'gate_authentication': {
    'github': {
      'token': '<GITHUB_TOKEN>'
    }
  }
}
```

I think support for token is enough and can be improved with full oauth authentication.

**Comment by jvasallo** [comment]
Resolved in #386! Thanks!
