### ISSUE TITLE
Spinnaker pipeline template support

### ISSUE THREAD

**Issue by KeisukeYamashita** [foremast/foremast#390]
## What

It will be great if foremast can support saving pipeline template.
foremast can offer pipeline template "template" features, a template for pipeline templates.

**Comment by linjmeyer** [comment]
Hi!  Does the [Spin CLI ](https://www.spinnaker.io/guides/spin/) not work for your use case?  We have a sort-of competing templating engine in Foremast with the manual pipeline templates.  I'm not against adding support for Spinnaker's pipeline templates to Foremast just curious if the existing functionality or Spin CLI will work?
