### ISSUE TITLE
Shared mastered bucket but no common prefix

### ISSUE THREAD

**Issue by c0debreaker** [foremast/foremast#410]
I created an s3 bucket without a `common.` prefix by using these codes. In AWS S3, it was created as `s3bucket.example.dev.example.com`.

```
  "s3": {
    "path": "/",
    "bucket_acl": "private",
    "website": {
      "enabled": true,
      "index_suffix": "index.html",
      "error_document": "404.html"
    }
  }
```

On the client repo that will upload files to it, I used this code. However, pipeline was failing with this error `foremast.exceptions.SpinnakerAppNotFound`. I saw in the Jenkins job's console that it was looking for the s3 bucket with the `common.` prefix.

```
"shared_bucket_target": "s3bucketexample"
```

By adding the code below, it will create a bucket with `common.` prefix. But the dev team doesn't like the prefix `common.` 🤣

```
"shared_bucket_master": true,
```

So the questions are:
1. Can an s3 bucket without `common` prefix be shared to other repos?
2. Or was I missing any setting which will make it work?

**Comment by jvasallo** [comment]
If you set the way you initially had it, can you add:
https://foremast.readthedocs.io/en/latest/configuration_files/application_json.html#bucket-name

We are able to manage buckets by providing the name for it (whatever it might be) using this.

**Comment by c0debreaker** [comment]
Thank you Joel! I'll try it now.

Neil

**Comment by c0debreaker** [comment]
It worked! Thank you!
