### ISSUE TITLE
Step Function Triggers

### ISSUE THREAD

**Issue by waynetaylor** [foremast/foremast#459]
Foremast Pipeline now supports step functions and I have validated this is working. 

We need to implement mechanisms for triggering a step function to remove the manual adding of the triggers:

- API Gateway
- Event Bridge
- Lambda execution e.g. call step function

**Comment by jvasallo** [comment]
It sounds like two things are needed:
1. Lambda to trigger and stop StateMachines - permissions
2. EventBridge triggers on StateMachines - Trigger block in Statemachine section.
