### ISSUE TITLE
Supporting several domains during deployment of a resource

### ISSUE THREAD

**Issue by c0debreaker** [foremast/foremast#474]
We're in the process of migration to another domain name. Which part in Foremast must be updated so that when a resource like an EC2 instance is being deployed, another fqdn is added to Route53?

For example:

An apache web server is being deployed by default as **apache.web.stage.example.com**.

Let's assume the new domain is **acme.com**.

What we want to happen is to also add an entry in the Route53 **acme.com** zone so that it points to the same machine. That entry can be a CNAME to apache.web.stage.example.com.

apache.web.stage.acme.com   CNAME apache.web.stage.example.com

This way, the new FQDN and some applications that are still using the old domain will both work.

**Comment by linjmeyer** [comment]
I like this idea a lot, I think if we could support changing the formats option from:
```
'formats': {
        'domain': 'acme.com`
}
```
to:
```
'formats': {
     'domains': [ 'acme.com', 'example.com' ]
}
```

then update the code hitting DNS/Route53 to create both, this could be do-able.  I think both would be CNAMEs pointing to the aws resource, rather than acme.com CNAME -> example.com but that would work the same as you describe.  Only down side I can think of is that this would enable the second domain for ALL pipelines, but if you are migrating off that may be desired anyway.

**Comment by c0debreaker** [comment]
That is awesome! Thank you for responding right away! :)

**Comment by c0debreaker** [comment]
Forgot to ask, where is that formats found? Which file is it?

**Comment by jvasallo** [comment]
@c0debreaker I saw a response in email, but didn't see it here, but for where `formats` section is located at is in your config.py settings:
https://github.com/foremast/foremast-template-examples/blob/master/configs/config.py#L59

To address the issue @linjmeyer mentioned:
`Only down side I can think of is that this would enable the second domain for ALL pipelines, but if you are migrating off that may be desired anyway.`

My thought in the pipeline.json (or application-<env>.json), you can have a section like `domains`, where engineers are able to specify what domains to create DNS records in (default: if not provided create in all domains listed in config.py). If you specify domains in the pipeline.json file, they are evaluated against the config.py list to ensure they are "supported." 

This enables both parties to both:
1. Support multiple domains
2. Limit domain if you don't need/want it.

Hope this helps!

**Comment by c0debreaker** [comment]
Hey Joel. Neil Camara here. 😊 Yes, I deleted my question because I figured it out after looking at the code.

Really glad to see your solutions. Looks like putting it in the pipeline.json is nice because developer teams will have the final say on when their applications are ready to be migrated.

Thank you both for keeping this project alive! 💪
