### ISSUE TITLE
Foremast overwrites s3 event configuration when I use s3 lambda trigger

### ISSUE THREAD

**Issue by v-khvorostianyi** [foremast/foremast#475]
If several lambdas are looking at the same s3 bucket, to get triggered by s3 event the last one deployed overwrites everything that was set up, no matter it was previous s3 trigger configuration, sns trigger etc. It just wipeouts everything and leave only one s3 trigger corresponding to the latest deployed lambda.
would you imagine s3 bucket with several hundreds s3 notification setups...

**Comment by jvasallo** [comment]
Foremast is stateless in the sense that it doesn't keep a running configuration of your current state but rather your desired state. Also, the lambda pipeline's scope is really around the lambda itself not the S3 bucket. For that, the s3 pipeline exist; which not only can deploy to s3 but also manage the configuration of a bucket as well. The way I have solved this is to use the Foremast S3 pipeline to manage a target s3 bucket, and then registering multiple `lambda_configurations` against that master bucket:
https://foremast.readthedocs.io/en/latest/configuration_files/application_json.html#lambda_configurations

This way you can still use Foremast to deploy your lambda and the s3 bucket to manage the configuration of all the various lambda/notifications you might need triggered on specific paths.

**Comment by vkhvorostianyi** [comment]
But in that case s3 trigger looks useless. If one can configure everything using s3 pipeline and s3 trigger overwrites event configuration i just won't use the s3 tigger, there is no sense in that "stateless". And it's not obvious, so one can instantly broke the s3 event configuration because he was expecting conf update, not overwriting. And it's a real case.

**Comment by vkhvorostianyi** [comment]
if nobody's going to look into it, I can.

**Comment by vkhvorostianyi** [comment]
of course if it's valuable for the project
